version = 0.1

[default.deploy.parameters]
stack_name = "S3ToDynamoDB"
resolve_s3 = true
s3_bucket = "periferia-s3-demo" 
s3_prefix = "S3ToDynamoDB"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
profile = "DavidProgramer"
